export enum DocumentIdentifierEnum {
  AccessType = "$ACCESS_TYPE",
  CashCollections = "$CASH_COLLECTIONS",
  CashRegistration = "$CASH_REGISTRATION",
  DeliveryOrder = "$DELIVERY_ORDER",
  DocumentType = "$DOCUMENT_TYPE",
  OnlinePayment = "$ONLINE_PAYMENT",
  OrderOption = "$ORDER_OPTION",
  PaymentMethod = "$PAYMENT_METHOD",
  PaymentProvider = "$PAYMENT_PROVIDER",
  Products = "$PRODUCTS",
  Profiles = "$PROFILES",
  PurchaseOrder = "$PURCHASE_ORDER",
  Quotation = "$QUOTATION",
  ReceivedNotes = "$RECEIVED_NOTES",
  Sales = "$SALES",
  SalesClosure = "$SALES_CLOSURE",
  SalesInvoice = "$SALES_INVOICE",
  SalesOrder = "$SALES_ORDER",
  ShoppingCart = "$SHOPPING_CART",
  Users = "$USERS",
}
