export enum TransactionNoInitialEnum {
  AccessType = "AT",
  CashCollections = "CC",
  CashRegistration = "CR",
  DeliveryOrder = "DO",
  DocumentType = "DT",
  OnlinePayment = "OP",
  OrderOption = "OO",
  PaymentMethod = "PM",
  PaymentProvider = "PR",
  Products = "PD",
  Profiles = "PF",
  PurchaseOrder = "PO",
  Quotation = "QT",
  ReceivedNotes = "RN",
  Sales = "SL",
  SalesClosure = "SR",
  SalesInvoice = "SI",
  SalesOrder = "SO",
  ShoppingCart = "SC",
  Users = "US",
}
